### PR TITLE
Intial Porting of Python 2 Code to Python 3

### PR DESCRIPTION
**Pull request by roaldnefs**
This PR is porting the Python 2 code to Python 3 without losing compatibility for Python 2.7 according to https://python-future.org/futurize.html.

~**Note:** this PR is still work in progress!~

### Description:

Stage 1 will apply fixes to modernize the Python 2 code without changing the effect of the code. The goal of this stage is to create most of the diff for the entire porting process, but without introducing any bugs.

Stage 2 will add a dependency on the `future` package. The goal for stage 2 is to make further mostly safe changes to the Python 2 code to use Python 3 style code that still runs on Python 2 with the help of the appropriate builtins and utilities in `future`.

In stage 3 we will be separating text from bytes manually by prefixing all the string literals with either `b` or `u` accordingly. To ensure that these type behave similarly on Python 2 as on Python 3, we will wrap byte-strings or text in the `bytes` and `str` types from `future`.

After running `futurize`, we start by testing compatibility on Python 3 and making further code changes until it's fully compatible with Python 3. The next step is to make manual tweaks to the code to re-enable Python 2 compatibility.

### Action Items:

- [x] Drop support for Python 2.6 and older (#33 )
- [x] Stage 1 of `futurize` (_except for `vstruct/*`_)
- [x] Manually fix commented code and exception messages that aren't correctly ported by `futurize`.
- [ ] Merge stage 1 changes into master (_most of the diff, minimal to no impact_) 
- [ ] Stage 2 of `futurize` (_except for `vstruct/*`_)
- [ ] Merge stage 2 changes into master
- [ ] Stage 1 and 2 of `futurize` in `vstruct/*`
- [ ] Merge `futurize` changes in `vstruct/*` into master
- [ ] Separating text from bytes manually
- [ ] Test & make the code pass on Python 3
- [ ] Manually tweak to re-enable Python 2 compatibility
- [ ] Merge changes into master

### Additional Information:

This PR is part of fixing #15.

### CODE REVIEW

**Comment by roaldnefs** [comment]
@atlas0fd00m, let me know if you prefer the changes to be submitted in bigger chunks! If so, you can leave this PR open and I will add some additional changes later this week.

**Comment by atlas0fd00m** [comment]
thanks @roaldnefs , i don't know how much work it's going to take, and where the key break-overs will be.  please let me know how you think the phases should be merged.  this being a WIP, i don't want to merge in code that could break things, so please be explicit in when and why you want something merged in.
adding comments to me is helpful along the way, but unfortunately i'm not likely to be terribly quick to respond right now.  i'll try to get a response within a couple days or less.

**Comment by roaldnefs** [comment]
@atlas0fd00m, I've included some merge actions to the action list. After fixing the stage 1 issues I'll remove the `WIP` tag and let you know when it's save to merge the the changes. In the meanwhile I'll create a new Work In Progress PR for the following phase and rebase it onto master once the previous phase is merged. This will allows the changes to be merged in smaller chunks without accidentally pushing breaking changes.

**Comment by roaldnefs** [comment]
@atlas0fd00m this PR is ready to be merged! I'll create a new PR for the following phase and rebase it onto master once this PR is merged.

**Comment by atlas0fd00m** [comment]
thanks for parting it up, @roaldnefs and for the good work.

**Comment by meeas** [comment]
Excellent work @roaldnefs!  Before I start playing with it, is it fully functional in 3.x with this commit, acknowledging the additional milestones you listed above.

**Pull request merged**
