### PR TITLE
Pypi setup

### PR DESCRIPTION
**Pull request by Lytrix**
Thanks for creating this create tool! 

## Reason for this PR:
Our team wants to install rfcat the proper way and more easily in setup.py install_requirements instead having to use the depreciated —use-dependancy-links option and git+https://...:
so that it can be found here: https://pypi.org/search/?q=rfcat and be used with a simple
```
pip install rfcat
```

## I've got a test version up and running here (will be removed after a day) on the testpypi server:
https://testpypi.python.org/pypi/rfcattest
you can test it now with this install command:
```
pip install --index-url https://test.pypi.org/simple/ rfcattest
```

## Steps to take to add the package to the PyPi registry:
create the same user account on pypi and on testpypi:
https://pypi.python.org/pypi?:action=login_form
https://test.pypi.python.org/pypi?:action=login_form (this is the new test server, testpypi is the old one)

## I followed these steps:
https://packaging.python.org/tutorials/distributing-packages/
and this one to test:
https://packaging.python.org/guides/using-testpypi/#using-test-pypi

### Create a new package in the dist folder:
```
python setup.py sdist
```
### Upload to testpypi to test (warning! once uploaded you cannot change it, so you need version numbers to update the package after uploading!)
```
sudo pip install twine
twine upload --repository-url https://test.pypi.org/legacy/ dist/*
```

### To install it from testpypi (with use of subversioning):
```
pip install --index-url https://test.pypi.org/simple/ rfcat==1.0.1 
```

### If all works wel you can upload it to the official PyPi registry:
```
twine upload dist/*
```
This tutorial was quite helpful only the upload way is changed:
http://peterdowns.com/posts/first-time-with-pypi.html

## Suggestions

- Convert the readme.md to readme.rst, what is done in this PR, because the styling on PiPy with md is not really nice. (I used this conversion solution: https://bfroehle.com/2013/04/26/converting-md-to-rst/)
- Needs probably more testing. It works for our use case.

### CODE REVIEW

**Review by atlas0fd00m — APPROVED** [review]
looks great, thanks!

**Comment by Lytrix** [comment]
@atlas0fd00m Thanks for merging! only one last step to take: it is best if you create an account on pip to add a package to the pypi registry as the official maintainer by following the steps above. Then you can decide when a version 1.0.2 will be best to push to pipy. If you want me to do it, or need some help, let me know!

**Comment by atlas0fd00m** [comment]
@Lytrix , i'm having troubles while testing.  i'm not sure how to navigate this.  i'm running pyusb from the ubuntu deb repo.

Collecting pyusb>=1.0.0 (from rfcat==1.0.1)
  Could not find a version that satisfies the requirement pyusb>=1.0.0 (from rfcat==1.0.1) (from versions: )
No matching distribution found for pyusb>=1.0.0 (from rfcat==1.0.1)

**Comment by Lytrix** [comment]
@atlas0fd00m That is strange, I tried to get the same error by installing pyusb on OSX and on a 14 and 17 Ubuntu virtual machine and they can all find the pyusb package. What does it say when you do a `pip install pyusb?`

**Comment by atlas0fd00m** [comment]
works fine from standard pypi, just not test.  huh.  but does that interfere with the installed pyusb from .deb?

**Pull request merged**
