### PR TITLE
Fix packet output in Python 3

### PR DESCRIPTION
**Pull request by argilo**
On Python 3, `RFlisten` fails to print received packets:
```
TypeError                                 Traceback (most recent call last)
~/git/rfcat/rflib/__init__.py in <module>
      6 d.setMdmSyncWord(0x02dd4)
      7 d.makePktVLEN()
----> 8 d.RFlisten()

~/git/rfcat/rflib/chipcon_nic.py in RFlisten(self)
   1211             try:
   1212                 y, t = self.RFrecv()
-> 1213                 print("(%5.3f) Received:  %s  | %s" % (t, hexlify(y), makeFriendlyAscii(y)))
   1214 
   1215             except ChipconUsbTimeoutException:

~/git/rfcat/rflib/chipcon_nic.py in makeFriendlyAscii(instring)
     44         out.append( instring[ start: ] )
     45 
---> 46     return b''.join(out)
     47 
     48 

TypeError: sequence item 1: expected a bytes-like object, str found
```
I rewrote and simplified `makeFriendlyAscii` to correct this problem. It also now returns a string instead of bytes, to avoid being printed as `b'.......).\."u..'`. I also added `.decode()` after each call to `hexlify` to avoid the hex being printed as `b'010c0101019f8d29f55cef22750791'`.

After these changes, packets are printed the same in Python 2 and Python 3.

### CODE REVIEW

**Comment by atlas0fd00m** [comment]
thanks @argilo , i'm tempted to accept this just for the white-space cleanup. :)

i like the simplication, and i'm really happy to get strings instead of bytes.  however, it creates a new string for every character, which is very costly for Python (or at least it was in Python2).  could you take another go at it using lists and one string creation at the end?

in the interim, i just committed and pushed a new bit of code to solve this makeFriendlyAscii() bug.  please test and see if it's broken.

**Comment by argilo** [comment]
> i'm tempted to accept this just for the white-space cleanup.

The whitespace cleanup is in a separate commit, so you could still cherry-pick that.

**Comment by argilo** [comment]
@atlas0fd00m Your change does fix the crash; the only problem that remains is that the bytes are printed in their `repr()` form:

```
(1601174272.130) Received:  b'010a010101b8143d7533b98626db8f'  | b'.......=u3..&..'
(1601174284.359) Received:  b'010c0101019f8d29f55cef22750791'  | b'.......).\\."u..'
(1601174291.225) Received:  b'010d010101e9395df5c4cb7a32219f'  | b'......9]...z2!.'
```

**Comment by argilo** [comment]
I'll close off this pull request for now, since the problems it was meant to solve are mostly gone now.

**Comment by atlas0fd00m** [comment]
@argilo thank you for your submission.  we can make the output a string if that makes sense.  i'm still getting my sea-legs with strings and bytes with py3.  what do you think?

**Pull request closed without merging**
